vti_encoding:SR|utf8-nl
vti_author:SR|THEZDIN\\Jacob P. Litwicki
vti_modifiedby:SR|THEZDIN\\Jacob P. Litwicki
vti_timelastmodified:TR|04 May 2005 05:07:35 -0000
vti_timecreated:TR|02 May 2005 20:11:25 -0000
vti_title:SR|thezdinMEDIA - Creative Business Media Solutions
vti_extenderversion:SR|6.0.2.6353
vti_backlinkinfo:VX|quote.php index.php form_success.php error.php template.html about.php portfolio.php services.php testimonials.php
vti_nexttolasttimemodified:TW|04 May 2005 05:06:03 -0000
vti_cacheddtm:TX|04 May 2005 05:07:35 -0000
vti_filesize:IR|14289
vti_cachedtitle:SR|thezdinMEDIA - Creative Business Media Solutions
vti_cachedbodystyle:SR|<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" onload="preloadImages();">
vti_cachedlinkinfo:VX|S|images/tm002_01.gif S|images/spacer.gif S|images/tm002_02.gif H|index.php S|images/tm002_03.gif S|images/tm002_04.gif S|images/tm002_06.gif S|images/spacer.gif S|images/spacer.gif H|inc/pronounce.wav S|images/tm002_17.gif S|images/tm002_18.gif S|images/spacer.gif S|images/tm002_19.gif S|images/spacer.gif S|images/spacer.gif H|about.php S|images/tm002_25.gif H|services.php S|images/tm002_26.gif H|portfolio.php S|images/tm002_27.gif H|quote.php S|images/tm002_28.gif S|images/tm002_29.gif H|testimonials.php S|images/tm002_30.gif H|index.php S|images/tm002_31.gif S|images/spacer.gif S|images/tm002_32.gif S|images/spacer.gif S|images/tm002_33.gif S|images/tm002_34.gif S|images/tm002_35.gif S|images/tm002_36.gif S|images/tm002_37.gif H|testimonials.php S|images/testmonial.gif S|images/tm002_38.gif S|images/spacer.gif S|images/tm002_39.gif S|images/spacer.gif S|images/tm002_40.gif S|images/spacer.gif S|images/tm002_41.gif H|services.php H|services.php S|images/business_work_comp.gif S|images/spacer.gif K|index.php S|images/tm002_42.gif K|index.php S|images/spacer.gif S|images/tm002_43.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif
vti_cachedsvcrellinks:VX|FSUS|images/tm002_01.gif FSUS|images/spacer.gif FSUS|images/tm002_02.gif FHUS|index.php FSUS|images/tm002_03.gif FSUS|images/tm002_04.gif FSUS|images/tm002_06.gif FSUS|images/spacer.gif FSUS|images/spacer.gif NHUS|inc/pronounce.wav FSUS|images/tm002_17.gif FSUS|images/tm002_18.gif FSUS|images/spacer.gif FSUS|images/tm002_19.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FHUS|about.php FSUS|images/tm002_25.gif FHUS|services.php FSUS|images/tm002_26.gif FHUS|portfolio.php FSUS|images/tm002_27.gif FHUS|quote.php FSUS|images/tm002_28.gif FSUS|images/tm002_29.gif FHUS|testimonials.php FSUS|images/tm002_30.gif FHUS|index.php FSUS|images/tm002_31.gif FSUS|images/spacer.gif FSUS|images/tm002_32.gif FSUS|images/spacer.gif FSUS|images/tm002_33.gif FSUS|images/tm002_34.gif FSUS|images/tm002_35.gif FSUS|images/tm002_36.gif FSUS|images/tm002_37.gif FHUS|testimonials.php FSUS|images/testmonial.gif FSUS|images/tm002_38.gif FSUS|images/spacer.gif FSUS|images/tm002_39.gif FSUS|images/spacer.gif FSUS|images/tm002_40.gif FSUS|images/spacer.gif FSUS|images/tm002_41.gif FHUS|services.php FHUS|services.php FSUS|images/business_work_comp.gif FSUS|images/spacer.gif FKUS|index.php FSUS|images/tm002_42.gif FKUS|index.php FSUS|images/spacer.gif FSUS|images/tm002_43.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif FSUS|images/spacer.gif
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Language en-us HTTP-EQUIV=Content-Type text/html;\\ charset=windows-1252 keywords web,\\ design,\\ website,\\ webdesign,\\ development,\\ services,\\ media,\\ print,\\ php,\\ asp,\\ html,\\ dhtml,\\ xml,\\ rss,\\ database,\\ ecommerce,\\ chicago,\\ modern,\\ internet description Creative\\ Business\\ Media\\ Solutions.\\ Offering\\ a\\ wide\\ variety\\ of\\ web\\ and\\ print\\ media\\ development\\ services.\\ A\\ small\\ startup\\ company\\ in\\ Chicagoland\\ Illinois.
vti_charset:SR|windows-1252
vti_language:SR|en-us
